name: locaitions-api-dev
on:
  push:
    branches: ["dev"]
  pull_request:
    branches: ["dev"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up python 3.11
        uses: actions/setup-python@v3
        with:
          python-version: "3.11"
      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
  deploy:
    needs: build
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2 

      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.AWS_EC2_PEM }}" > ~/.ssh/my-ec2-key
          chmod 600 ~/.ssh/my-ec2-key
          ssh-keyscan -H "${{ secrets.AWS_EC2_PUBLIC_IP }}" >> ~/.ssh/known_hosts
      - name: SSH to EC2 and run commands
        run: |
          ssh -i ~/.ssh/my-ec2-key -o "StrictHostKeyChecking no" ubuntu@${{ secrets.AWS_EC2_PUBLIC_IP }} << EOF
            cd ~/locaitions-be-api/
            source env/bin/activate
            pip install -r requirements.txt
            git checkout aws-portable-keys-connection &&
            git fetch --all &&
            git reset --hard origin/dev &&
            git pull origin dev &&
            python3 -m uvicorn main:app --reload
          EOF || echo "Failed to SSH and run commands"
